---
title: "Homework 3"
author: "Maria Alfaro"
date: "2/2/2022"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Home Page](index.html)

## Problem 1
```
FIND: \h\h+
REPLACE: ,
```
I used the h wildcard to find white spaces in 2 or more consecutive chunks that were not line breaks (s wildcard includes line breaks) and replaced them with commas.


## Problem 2
```
FIND: (\w+,)\s(\w+),\s(\w+.*)
REPLACE: \2 \1 \(\3\)
```
I basically used the w and s wildcards to capture each line and then capture elements to rearrange them and add parentheses.


## Problem 3
```
FIND: .mp3\s0
REPLACE: .mp3\n0
```
I located the space between tracks because it has predictable/unique alphanumeric chunks before and after, and I replaced it with a line break (n wildcard).


## Problem 4
```
FIND:(\d+)\s(\w+.*)(.mp3)
REPLACE: \2_\1\3
```
I broke each line into 1. a numerical chunk with the d wildcard 2. the song title using a combination of the w wildcard and the "all the rest": .* and 3. .mp3, and then rearranged the terms and added an underscore.


## Problem 5
```
FIND: (\w)\w+,(\w+),\d+.\d+(,\d+)
REPLACE: \1_\2\3
```
I captured the first letter of the genus, the specific epithet, and the second number and left behind the rest and added an underscore.


## Problem 6
```
FIND: (\w)\w+,(\w{4})\w+,\d+.\d(,\d+)
REPLACE: \1_\2\3
```
I captured the first letter of the genus, the first four letters of the specific epithet, and the second number. I left behind everything else and added an underscore.


## Problem 7
```
FIND: (\w{3})\w+,(\w{3})\w+,(\d+.\d),(\d+)
REPLACE: \1\2, \4, \3
```
I captured the first three letters of the genus, the first three letters of the specific epithet, the first number (with a decimal), and the second number. I switched the places of the numbers and left everything else behind.



